CREATE SCHEMA BRE;

--DROP TABLE BRE.INCOMING_RISK_EVENTS;
CREATE TABLE BRE.INCOMING_RISK_EVENTS 
(
	SYSTEM_ID     					INTEGER NOT NULL
	, EVENT_CATEGORY_ID				INTEGER NOT NULL
	, IHUB_MERCHANT_ID				BIGINT NOT NULL
	, WORKER_ID						INTEGER NOT NULL	
	, MERCHANT_ACCOUNT_NUMBER 		VARCHAR(64) NOT NULL
	, EVENT_DATE					DATE	
	, EVENT_TYPE_ID					INTEGER NOT NULL
	, EVENT_ID 						INTEGER NOT NULL
	, EVENT_DETAILS					VARCHAR(1024)	
	, RETRIES						INTEGER	DEFAULT -1 NOT NULL
	, PROCESSING_STATUS				INTEGER DEFAULT 0 NOT NULL 
	, ERROR_MSG						VARCHAR(4000) DEFAULT '' 
	, EVENT_TIMESTAMP				TIMESTAMP NOT NULL	
	, TIME_QUEUED					TIMESTAMP	
	, TIME_DE_QUEUED				TIMESTAMP NOT NULL
	, TIME_PROCESSED				TIMESTAMP
	, TIME_RETRY_1					TIMESTAMP
	, TIME_RETRY_2					TIMESTAMP
	, PRIMARY KEY(SYSTEM_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_CATEGORY_ID, EVENT_TYPE_ID, EVENT_ID)
);
